# used for local development
# To build the app image, you can run the spring-boot:build-image goal with the native profile active: mvn -Pnative spring-boot:build-image

version: '3.9'
services:
  app:
    image: urlshortener:0.0.1-SNAPSHOT
#    build: .
    ports:
      - "9090:9090"
    links:
      - redis
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
  redis:
    image: 'redis/redis-stack:latest'
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
